アプリの国際化対応
YukiWatanabe824/fjord-books_app pull request #1
Opened 2022-07-09 07:42 UTC by YukiWatanabe824

gemの追加、抽象化、訳文追加

2022-07-14 09:23 UTC, komagata requested changes

2022-07-14 09:23 UTC, komagata commented on config/locales/ja.yml
> +  translate:
全てのlocalesディレクトリ以下のファイルがtranslateのためのファイルなのでキーに`translate`は不要かもしれません。

2022-07-14 09:23 UTC, komagata commented on config/locales/ja.yml
> +  bookcreate:
```yml
book:
  create: 
    success: 作成しました
```

`bookcreate`だと文字の区切りがわからないので上記のように構造化した方がいいかもしれません。

2022-07-17 08:46 UTC, YukiWatanabe824 commented on config/locales/ja.yml
> +  translate:
階層を設けたほうが情報が整理されてわかりやすいだろうと思ったのですが、いい言葉が浮かばずに`translate`にしました。
別の言葉に置き換えます💦

2022-07-17 08:47 UTC, YukiWatanabe824 commented on config/locales/ja.yml
> +  bookcreate:
ご指摘ありがとうございます。
修正します！

2022-07-17 16:54 UTC, komagata requested changes

2022-07-17 16:54 UTC, komagata commented on config/locales/ja.yml
> +  book_app:
このアプリ全てがbook_appだと思うので、特にprefixをつける必要のないものでしたら階層化しないでいいのではないでしょうか。

Rubyでは「名前重要」というのが特に言われる言語なので、ふさわしい名前を考えるためには一番時間を使ってしまって大丈夫です。（それにrubyプログラマーのみんなは一番名前に頭を使っています）

2022-07-18 15:58 UTC, YukiWatanabe824 commented on config/locales/ja.yml
> +  book_app:
たしかに階層化するのが半ば目的になっていたように思います。特にプレフィックスが必要な場面はないので消してしまいます。

名前重要の考え方、初めて知りました。
Matzさんの言葉だったんですね。今後意識していきます。

2022-07-19 07:58 UTC, komagata requested changes

2022-07-19 07:58 UTC, komagata commented on app/views/books/index.html.erb
> +      <th><%= t('book_title') %></th>
bookのtitleなのでbookは不要かと思います。また、下記の他のものにはbookがついていないので統一されていないのが気になります。

`activerecord.attributes.book.title`に既にあるのでそちらを使うといいと思います。

またそれらは`Model名.human_attribute_name`で使えるのでこのメソッドを調べてみてください〜

2022-07-24 06:28 UTC, YukiWatanabe824 commented on app/views/books/index.html.erb
> +      <th><%= t('book_title') %></th>
translation_ja.ymlの方はぜんぜん中身を見ていませんでした💦
`.human_attribute_name`についても調べて、導入してみました。

2022-07-25 18:00 UTC, komagata approved these changes
確認させて頂きました。OKです〜🙆‍♂️

2022-07-26 21:37 UTC, merged